[package]
name = "synaptix-image-sdxl"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "SDXL."

[features]
default = []
cuda = []

[dependencies]
synaptix-core      = { workspace = true }
synaptix-ops       = { workspace = true }
synaptix-nn        = { workspace = true }
synaptix-tokenizer = { workspace = true }
synaptix-bundle    = { workspace = true }
synaptix-config    = { workspace = true }
synaptix-io        = { workspace = true }
synaptix-diffusion = { workspace = true }
thiserror          = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }
regex              = { workspace = true }

[dev-dependencies]
synaptix-kernels-cpu = { workspace = true }
synaptix-test-utils  = { workspace = true }
