pub mod bbox_head;
pub mod cls_head;
pub mod ctc_head;
pub mod keypoint_head;
pub mod lm_head;
pub mod mlm_head;
pub mod qa_head;
pub mod regression_head;
pub mod reward_head;
pub mod rnn_t_head;
pub mod segmentation_head;
pub mod token_cls_head;
pub mod value_head;

pub use bbox_head::BboxHead;
pub use cls_head::ClassificationHead;
pub use ctc_head::CtcHead;
pub use keypoint_head::KeypointHead;
pub use lm_head::LmHead;
pub use mlm_head::MlmHead;
pub use qa_head::QaHead;
pub use regression_head::{RegressionActivation, RegressionHead};
pub use reward_head::RewardHead;
pub use rnn_t_head::RnnTHead;
pub use segmentation_head::SegmentationHead;
pub use token_cls_head::TokenClsHead;
pub use value_head::ValueHead;
