use crate::ir::{IrGraph, IrOp};

pub struct CudaCodegen {
    pub arch: String,
    pub include_headers: bool,
}

impl CudaCodegen {
    pub fn new(arch: &str) -> Self {
        Self { arch: arch.into(), include_headers: true }
    }

    pub fn without_headers(mut self) -> Self {
        self.include_headers = false;
        self
    }
}

impl crate::codegen::Codegen for CudaCodegen {
    fn generate(&self, g: &IrGraph) -> crate::error::Result<String> {
        let mut s = String::new();
        if self.include_headers {
            s.push_str("// Generated by synaptix-compile::codegen::CudaCodegen\n");
            s.push_str(&format!("// arch: {}\n", self.arch));
            s.push_str("#include <cuda_runtime.h>\n#include <cuda_fp16.h>\n#include <cuda_bf16.h>\n\n");
        }
        let mut params: Vec<&String> = g.inputs.iter().chain(g.outputs.iter()).collect();
        params.sort();
        params.dedup();
        let sig = if params.is_empty() {
            "void synaptix_fwd()".to_string()
        } else {
            let args = params.iter().map(|n| format!("float* {n}")).collect::<Vec<_>>().join(", ");
            format!("extern \"C\" __global__ void synaptix_fwd({args})")
        };
        s.push_str(&sig);
        s.push_str(" {\n");
        for (i, op) in g.ops.iter().enumerate() {
            s.push_str(&format!("    // op[{i}]: {}\n", op_summary(op)));
            s.push_str(&op_inline_stub(op, "    "));
        }
        s.push_str("}\n");
        Ok(s)
    }
}

fn op_summary(op: &IrOp) -> String {
    match op {
        IrOp::MatMul { a, b, out } => format!("MatMul({a},{b}) -> {out}"),
        IrOp::Add { a, b, out } => format!("Add({a},{b}) -> {out}"),
        IrOp::Relu { inp, out } => format!("Relu({inp}) -> {out}"),
        IrOp::Softmax { inp, dim, out } => format!("Softmax(dim={dim}, {inp}) -> {out}"),
        IrOp::LayerNorm { inp, weight, bias, out } => {
            format!("LayerNorm({inp}, w={weight}, b={bias}) -> {out}")
        }
        IrOp::Fused(ops) => format!("Fused({} ops)", ops.len()),
    }
}

fn op_inline_stub(op: &IrOp, indent: &str) -> String {
    let mut s = String::new();
    match op {
        IrOp::MatMul { out, .. } => s.push_str(&format!("{indent}/* MatMul -> {out}: requires GEMM kernel link */\n")),
        IrOp::Add { a, b, out } => {
            s.push_str(&format!("{indent}/* Elementwise add: out = a + b */\n"));
            s.push_str(&format!(
                "{indent}// for (int i = ...; ...) {out}[i] = {a}[i] + {b}[i];\n"
            ));
        }
        IrOp::Relu { inp, out } => {
            s.push_str(&format!(
                "{indent}// for (int i = ...; ...) {out}[i] = fmaxf({inp}[i], 0.0f);\n"
            ));
        }
        IrOp::Softmax { out, .. } => {
            s.push_str(&format!("{indent}/* Softmax -> {out}: requires block-reduce kernel */\n"));
        }
        IrOp::LayerNorm { out, .. } => {
            s.push_str(&format!("{indent}/* LayerNorm -> {out}: requires fused reduce + affine */\n"));
        }
        IrOp::Fused(ops) => {
            for inner in ops {
                s.push_str(&op_inline_stub(inner, &format!("{indent}    ")));
            }
        }
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::Codegen;

    #[test]
    fn empty_graph_emits_signature() {
        let g = IrGraph::new();
        let src = CudaCodegen::new("sm_80").generate(&g).unwrap();
        assert!(src.contains("synaptix_fwd"));
        assert!(src.contains("arch: sm_80"));
    }

    #[test]
    fn matmul_op_appears_in_source() {
        let mut g = IrGraph::new();
        g.inputs.push("x".into());
        g.inputs.push("w".into());
        g.outputs.push("y".into());
        g.push(IrOp::MatMul { a: "x".into(), b: "w".into(), out: "y".into() });
        let src = CudaCodegen::new("sm_90").generate(&g).unwrap();
        assert!(src.contains("MatMul"));
        assert!(src.contains("float* x"));
        assert!(src.contains("float* w"));
        assert!(src.contains("float* y"));
        assert!(src.contains("op[0]"));
    }

    #[test]
    fn relu_emits_indicative_comment() {
        let mut g = IrGraph::new();
        g.inputs.push("x".into());
        g.outputs.push("y".into());
        g.push(IrOp::Relu { inp: "x".into(), out: "y".into() });
        let src = CudaCodegen::new("sm_120").generate(&g).unwrap();
        assert!(src.contains("fmaxf"));
        assert!(src.contains("y[i]"));
        assert!(src.contains("x[i]"));
    }

    #[test]
    fn without_headers_no_includes() {
        let g = IrGraph::new();
        let src = CudaCodegen::new("sm_80").without_headers().generate(&g).unwrap();
        assert!(!src.contains("#include"));
    }
}
