use crate::ir::{IrGraph, IrOp};

pub struct PtxCodegen {
    pub arch: String,
    pub address_size: u32,
}

impl PtxCodegen {
    pub fn new(arch: &str) -> Self {
        Self { arch: arch.into(), address_size: 64 }
    }
}

impl crate::codegen::Codegen for PtxCodegen {
    fn generate(&self, g: &IrGraph) -> crate::error::Result<String> {
        let target = derive_target(&self.arch)
            .ok_or_else(|| crate::error::CompileError::Codegen(format!("PTX: unknown arch '{}'", self.arch)))?;
        let mut s = String::new();
        s.push_str("//\n// Generated by synaptix-compile::codegen::PtxCodegen\n");
        s.push_str(&format!("// arch: {}, sm: {}\n//\n\n", self.arch, target.sm));
        s.push_str(&format!(".version {}\n", target.ptx_version));
        s.push_str(&format!(".target {}\n", target.sm_directive));
        s.push_str(&format!(".address_size {}\n\n", self.address_size));

        let mut params: Vec<&String> = g.inputs.iter().chain(g.outputs.iter()).collect();
        params.sort();
        params.dedup();
        s.push_str(".visible .entry synaptix_fwd");
        if params.is_empty() {
            s.push_str(" ()\n");
        } else {
            s.push_str(" (\n");
            for (i, p) in params.iter().enumerate() {
                let sep = if i + 1 < params.len() { "," } else { "" };
                s.push_str(&format!("    .param .u64 param_{p}{sep}    // {p}\n"));
            }
            s.push_str(")\n");
        }
        s.push_str("{\n");
        s.push_str("    // PTX skeleton: real op-codegen требует разрешения shape/dtype\n");
        s.push_str("    // и привязки к мat-mul/elementwise tile-стратегии. Здесь только IR-аннотации.\n");
        for (i, op) in g.ops.iter().enumerate() {
            s.push_str(&format!("    // op[{i}]: {}\n", op_summary(op)));
        }
        s.push_str("    ret;\n");
        s.push_str("}\n");
        Ok(s)
    }
}

struct PtxTarget {
    sm: u32,
    sm_directive: String,
    ptx_version: String,
}

fn derive_target(arch: &str) -> Option<PtxTarget> {
    let a = arch.trim().to_ascii_lowercase();
    let sm = if let Some(rest) = a.strip_prefix("sm_") {
        let stripped: String = rest.chars().take_while(|c| c.is_ascii_digit()).collect();
        stripped.parse::<u32>().ok()?
    } else if a == "ampere" {
        80
    } else if a == "hopper" {
        90
    } else if a == "blackwell" {
        120
    } else {
        return None;
    };
    let ptx_version = if sm >= 120 {
        "8.5".to_string()
    } else if sm >= 90 {
        "8.0".to_string()
    } else if sm >= 80 {
        "7.5".to_string()
    } else {
        "7.0".to_string()
    };
    let sm_directive = if a == "sm_120a" {
        "sm_120a".to_string()
    } else {
        format!("sm_{sm}")
    };
    Some(PtxTarget { sm, sm_directive, ptx_version })
}

fn op_summary(op: &IrOp) -> String {
    match op {
        IrOp::MatMul { a, b, out } => format!("MatMul({a},{b}) -> {out}"),
        IrOp::Add { a, b, out } => format!("Add({a},{b}) -> {out}"),
        IrOp::Relu { inp, out } => format!("Relu({inp}) -> {out}"),
        IrOp::Softmax { inp, dim, out } => format!("Softmax(dim={dim}, {inp}) -> {out}"),
        IrOp::LayerNorm { inp, weight, bias, out } => {
            format!("LayerNorm({inp}, w={weight}, b={bias}) -> {out}")
        }
        IrOp::Fused(ops) => format!("Fused({} ops)", ops.len()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::Codegen;

    #[test]
    fn empty_graph_emits_valid_skeleton() {
        let g = IrGraph::new();
        let src = PtxCodegen::new("sm_120").generate(&g).unwrap();
        assert!(src.contains(".version"));
        assert!(src.contains(".target sm_120"));
        assert!(src.contains(".address_size 64"));
        assert!(src.contains(".visible .entry synaptix_fwd"));
        assert!(src.contains("ret;"));
    }

    #[test]
    fn arch_aliases_resolve() {
        let s_hopper = PtxCodegen::new("hopper").generate(&IrGraph::new()).unwrap();
        assert!(s_hopper.contains(".target sm_90"));
        assert!(s_hopper.contains(".version 8.0"));
        let s_amp = PtxCodegen::new("ampere").generate(&IrGraph::new()).unwrap();
        assert!(s_amp.contains(".target sm_80"));
    }

    #[test]
    fn sm_120a_preserves_a_suffix() {
        let src = PtxCodegen::new("sm_120a").generate(&IrGraph::new()).unwrap();
        assert!(src.contains(".target sm_120a"));
        assert!(src.contains(".version 8.5"));
    }

    #[test]
    fn matmul_op_emitted_as_comment() {
        let mut g = IrGraph::new();
        g.push(IrOp::MatMul { a: "a".into(), b: "b".into(), out: "c".into() });
        let src = PtxCodegen::new("sm_90").generate(&g).unwrap();
        assert!(src.contains("op[0]: MatMul"));
    }

    #[test]
    fn unknown_arch_errors() {
        let err = PtxCodegen::new("zorblax_9000").generate(&IrGraph::new());
        assert!(err.is_err());
    }
}
